const WORDPRESS_PASSWORD = 'WORDPRESS_PASSWORD' 
const WORDPRESS_WEBSITE_ADDRESS = 'WORDPRESS_WEBSITE_ADDRESS'
const WORDPRESS_REST_API = 'WORDPRESS_REST_API'


module.exports = { 
  WORDPRESS_PASSWORD,
  WORDPRESS_WEBSITE_ADDRESS,
  WORDPRESS_REST_API
};